[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748363

[[patches]] #G.GAME
[patches.pattern]
target = 'game.lua'
pattern = '''
'''
position = 'after'
match_indent = true
payload = '''
'''
